package com.hfnu.zl.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * 此类为greendao设置字段后自动创建 大大方便了代码的书写
 * 账本实体类 实现了Serializable界面 可用于intent传输
 */
@Entity
public class AccountBook implements java.io.Serializable {

    @Id
    private Long id;//
    private String type;//正本类型
    private Boolean turnover;//是支出还是收入
    private String use;//用途或来源
    private Float money;//钱数
    private java.util.Date writeTime;//账单时间
    private String remark;//备注

    @Generated
    public AccountBook() {
    }

    public AccountBook(Long id) {
        this.id = id;
    }

    @Generated
    public AccountBook(Long id, String type, Boolean turnover, String use, Float money, java.util.Date writeTime, String remark) {
        this.id = id;
        this.type = type;
        this.turnover = turnover;
        this.use = use;
        this.money = money;
        this.writeTime = writeTime;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getTurnover() {
        return turnover;
    }

    /**
     * 自己增加的方法
     * 用于将支出或收入转换成加减号
     * @return
     */
    public String getTurnoverSymbol() {
        return this.turnover?"-":"+";
    }
    public void setTurnover(Boolean turnover) {
        this.turnover = turnover;
    }
    /**
     * 自己增加的方法
     * 用于将支出或收入转换true或者false
     * @return
     */
    public void setTurnoverText(String turnoverText){
        this.turnover=turnoverText.equals("支出")?true:false;
    }
    public String getUse() {
        return use;
    }

    public void setUse(String use) {
        this.use = use;
    }

    public Float getMoney() {
        return money;
    }

    public void setMoney(Float money) {
        this.money = money;
    }

    public java.util.Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(java.util.Date writeTime) {
        this.writeTime = writeTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
