package com.hfnu.zl.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryDaoConfig;
    private final DaoConfig accountBookDaoConfig;
    private final DaoConfig scheduleDaoConfig;

    private final DiaryDao diaryDao;
    private final AccountBookDao accountBookDao;
    private final ScheduleDao scheduleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        accountBookDaoConfig = daoConfigMap.get(AccountBookDao.class).clone();
        accountBookDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        diaryDao = new DiaryDao(diaryDaoConfig, this);
        accountBookDao = new AccountBookDao(accountBookDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);

        registerDao(Diary.class, diaryDao);
        registerDao(AccountBook.class, accountBookDao);
        registerDao(Schedule.class, scheduleDao);
    }
    
    public void clear() {
        diaryDaoConfig.clearIdentityScope();
        accountBookDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

    public AccountBookDao getAccountBookDao() {
        return accountBookDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

}
