package com.hfnu.zl.database;

import org.greenrobot.greendao.annotation.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * 此类为greendao设置字段后自动创建 大大方便了代码的书写
 * 日记实体类 实现了Serializable界面 可用于intent传输
 */
@Entity
public class Diary implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;//日记ID
    private String passWord;//日记密码
    private String diaryType;//日记类型 如：旅行日记 成行日记。。。
    private String picture;//照片路径集合
    private String content;//日记内容
    private String record;//录音路径集合
    private String mood;//心情
    private java.util.Date writeTime;//写日记时间  在数据中存储的是时间戳

    @Generated
    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    @Generated
    public Diary(Long id, String passWord, String diaryType, String picture, String content, String record, String mood, java.util.Date writeTime) {
        this.id = id;
        this.passWord = passWord;
        this.diaryType = diaryType;
        this.picture = picture;
        this.content = content;
        this.record = record;
        this.mood = mood;
        this.writeTime = writeTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getDiaryType() {
        return diaryType;
    }
    /**
     * 自己写的设置照片集合方法
     * @param pictureList
     */
    public void setPictureList(List<String> pictureList) {
        if (!pictureList.isEmpty()) {
            for (int i = 0; i < pictureList.size(); i++) {
                if (this.picture == null)
                    this.picture = "";
                if (i == pictureList.size() - 1) {
                    this.picture += pictureList.get(i);
                } else
                    this.picture += pictureList.get(i) + "wynklmn";//将所有的照片路径用wynklmn拼接起来
            }
        }
    }
    /**
     * 自己写的获取照片集合的方法
     * @return
     */
    public List<String> getPictureList() {
        if (picture != null&&!picture.isEmpty()) {
            return Arrays.asList(picture.split("wynklmn"));//将照片路径字符全用wynklmn分割成数组 再添加在集合中
        } else
            return new ArrayList<String>();
    }
    /**
     * 自己写的设置录音集合的方法
     * @return
     */
    public void setRecordList(List<String> recordList) {
        if (!recordList.isEmpty()) {
            for (int i = 0; i < recordList.size(); i++) {
                if (this.record == null)
                    this.record = "";
                if (i == recordList.size() - 1) {
                    this.record += recordList.get(i);
                } else
                    this.record += recordList.get(i) + "wynklmn";//将所有的录音路径用wynklmn拼接起来
            }
        }
    }

    /**
     * 自己写的获取录音集合的方法
     * @return
     */
    public List<String> getRecordList() {
        if (record != null&&!record.isEmpty()) {
            return Arrays.asList(record.split("wynklmn"));//将录音路径字符全用wynklmn分割成数组 再添加在集合中
        } else
            return new ArrayList<String>();
    }


    public void setDiaryType(String diaryType) {
        this.diaryType = diaryType;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getRecord() {
        return record;
    }

    public void setRecord(String record) {
        this.record = record;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    public java.util.Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(java.util.Date writeTime) {
        this.writeTime = writeTime;
    }

}
