package com.hfnu.zl.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * 此类为greendao设置字段后自动创建 大大方便了代码的书写
 * 日程实体类 实现了Serializable界面 可用于intent传输
 */
@Entity
public class Schedule implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;//日程id
    private String scheduleName;//日程名称
    private java.util.Date writeTime;//日程时间
    private String detailContent;//日程描叙
    private String mood;//心情

    @Generated
    public Schedule() {
    }

    public Schedule(Long id) {
        this.id = id;
    }

    @Generated
    public Schedule(Long id, String scheduleName, java.util.Date writeTime, String detailContent, String mood) {
        this.id = id;
        this.scheduleName = scheduleName;
        this.writeTime = writeTime;
        this.detailContent = detailContent;
        this.mood = mood;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getScheduleName() {
        return scheduleName;
    }

    public void setScheduleName(String scheduleName) {
        this.scheduleName = scheduleName;
    }

    public java.util.Date getWriteTime() {
        return writeTime;
    }

    public void setWriteTime(java.util.Date writeTime) {
        this.writeTime = writeTime;
    }

    public String getDetailContent() {
        return detailContent;
    }

    public void setDetailContent(String detailContent) {
        this.detailContent = detailContent;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

}
